/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 28-Apr-2019 11:02:22
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 18
 * Denominator Length  : 18
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
 
 typedef struct{
	double raw_value;
	double xbuf[36];
	double ybuf[36];
	double filtered_value;
}Filter_t;
const int NL = 19;
const real64_T NUM[19] = {
  6.562360031457e-10,1.181224805662e-08,1.004041084813e-07,5.354885785669e-07,
  2.008082169626e-06,5.622630074952e-06, 1.21823651624e-05,2.088405456411e-05,
  2.871557502565e-05,3.190619447294e-05,2.871557502565e-05,2.088405456411e-05,
   1.21823651624e-05,5.622630074952e-06,2.008082169626e-06,5.354885785669e-07,
  1.004041084813e-07,1.181224805662e-08,6.562360031457e-10
};
const int DL = 19;
const real64_T DEN[19] = {
                   1,   -9.352753830238,    42.58193202362,   -124.8648903228,
      263.4382195793,   -423.6238144242,     537.036976171,   -547.9074620821,
        455.43718034,    -310.383940837,    173.6652855457,   -79.51646748485,
      29.55003656663,   -8.785898787317,    2.042745517883,  -0.3581714199149,
    0.04457593990634,-0.003512273390342,  0.00013180624249
};
float Chebyshev50HzLPF(Filter_t *F)
{
	int i;
	for(i=18; i>0; i--)
	{
		F->ybuf[i] = F->ybuf[i-1]; 
		F->xbuf[i] = F->xbuf[i-1];
	}
	F->xbuf[0] = F->raw_value;
	F->ybuf[0] = NUM[0] * F->xbuf[0];
	for(i=1;i<19;i++)
	{
		F->ybuf[0] = F->ybuf[0] + NUM[i] * F->xbuf[i] - DEN[i] * F->ybuf[i];
	}
	F->filtered_value = F->ybuf[0];
	return F->filtered_value;
}
